// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class UpdatedtheDateTimepropertyinmyMyPickupclasssothatwhenausercreatesapickupthedatetimeformatwillshowup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(UpdatedtheDateTimepropertyinmyMyPickupclasssothatwhenausercreatesapickupthedatetimeformatwillshowup));
        
        string IMigrationMetadata.Id
        {
            get { return "201812122216141_Updated the DateTime property in my MyPickup class so that when a user creates a pickup, the datetime format will show up"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
