// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CustomerindexviewdidntchangesoIdeletedthecustomerviewfolderagainalongwiththecustmercontrollerandthenaddedboth : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CustomerindexviewdidntchangesoIdeletedthecustomerviewfolderagainalongwiththecustmercontrollerandthenaddedboth));
        
        string IMigrationMetadata.Id
        {
            get { return "201808272315030_Customer indexview didn't change so I deleted the customer view folder again along with the custmer controller, and then added both."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
