// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditedtheMyPickupsclassbutkepttheTimepropertywhichIkeptandgotridoftheDayOfTheWeekproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedtheMyPickupsclassbutkepttheTimepropertywhichIkeptandgotridoftheDayOfTheWeekproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201812082104263_Edited the MyPickups class but kept the Time property which I kept and got rid of the DayOfTheWeek property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
