// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditedthecustomermodelandchangedtheVetAddresscolumntoVetHospitalNameandaddedacolumnVetHospitalAddress : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedthecustomermodelandchangedtheVetAddresscolumntoVetHospitalNameandaddedacolumnVetHospitalAddress));
        
        string IMigrationMetadata.Id
        {
            get { return "201808272310220_Edited the customer model and changed the VetAddress column to VetHospitalName, and added a column VetHospitalAddress"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
