// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditedthePaymentPlanClassandchangedittoMyPickupsandaddedthecorrectinformationforit : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedthePaymentPlanClassandchangedittoMyPickupsandaddedthecorrectinformationforit));
        
        string IMigrationMetadata.Id
        {
            get { return "201808282345595_Edited the Payment Plan Class and changed it to MyPickups and added the correct information for it"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
