// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditedtheDateTimepropertyinMyPickupclassandaddedadatatypeofdatetimetothatproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedtheDateTimepropertyinMyPickupclassandaddedadatatypeofdatetimetothatproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201812122242404_Edited the DateTime property in MyPickup class and added a datatype of datetime to that property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
