// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditedtheaccountviewmodelclassandaddedahelpermethodformyGmailAPI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedtheaccountviewmodelclassandaddedahelpermethodformyGmailAPI));
        
        string IMigrationMetadata.Id
        {
            get { return "201808222131234_Edited the accountviewmodel class and added a helper method for my Gmail API"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
