// <auto-generated />
namespace Capstone.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class EditedtheMyPickupsmodelandaddedaTimepropertythatusestheDateTimeclass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditedtheMyPickupsmodelandaddedaTimepropertythatusestheDateTimeclass));
        
        string IMigrationMetadata.Id
        {
            get { return "201812081954153_Edited the MyPickups model and added a Time property that uses the DateTime class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
